### ISSUE TITLE
[BUG]: looping email pooling

### ISSUE THREAD

**Issue by swxtz** [swxtz/athenas#108]
### Título do Bug

[BUG]: looping email pooling

### Descrição do Problema

está tendo um comportamento estranho quando remanda o email de verificar conta, uma fila esta apontando para outra fila que 
tenta mandar um email que ja foi mandando fazendo assim um looping de emails.

**Comment by RafaelRapozzo** [comment]
looping corrected, I was calling a function within itself, creating a loop.
